sudo: false
language: python
python:
- '2.7'
- '3.5'
- '3.6'
- '3.7'
- '3.8'
addons:
  apt:
    packages:
    - libeigen3-dev
install:
- pip install -r requirements.txt
- pip install pytest
- pip install -e .
script:
- pytest -v
notifications:
  slack:
    secure: AgUY/TLpOZ8srnEPBMAaRa2QmwwChN7V8HJT6LZcyJVsPVjv7EuashaUMPo7lhTWAqoTnCxCLNtsGkZGvVP3UeIpUJc/LIlGcUl7lD5x9uLHxvyT/5qsW9DS/i1MDQ3cKe6RhxPhe4m1EHRvEgBuv42K94kfNXOZys7Sla7nNWM=
