# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest]
        include:
          - platform: ubuntu-latest
            INSTALL_DEPS: sudo apt-get install libeigen3-dev
          - platform: macos-latest
            INSTALL_DEPS: brew install eigen
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    runs-on: ${{ matrix.platform }}
        
    steps:
      - uses: actions/checkout@v4
      # - name: Setup upterm session
      #   uses: lhotari/action-upterm@v1
      #   if: ${{ failure() }}
      #   with:
      #     ## If no one connects after 5 minutes, shut down server.
      #     wait-timeout-minutes: 5
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install eigen
        run: ${{ matrix.INSTALL_DEPS }}
      - name: Install dependencies
        run: python -m pip install --upgrade pip wheel setuptools
      - name: Build and install
        run: python -m pip install --verbose .[test]
      - name: Test with pytest
        run: pytest -v
