# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-15-intel, macos-latest, ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14", "pypy3.10", "pypy3.11"]
        include:
        - platform: ubuntu-latest
          INSTALL_DEPS: sudo apt-get install libeigen3-dev
        - platform: macos-latest
          INSTALL_DEPS: brew install eigen
        - platform: macos-15-latest
          INSTALL_DEPS: brew install eigen
    runs-on: ${{ matrix.platform }}
        
    steps:
    - uses: actions/checkout@v6
    - name: Install uv
      uses: astral-sh/setup-uv@v7
    - name: Install eigen
      run: ${{ matrix.INSTALL_DEPS }}
    - name: Install dependencies
      run: uv sync --frozen
    - name: Run tests on python ${{ matrix.python-version }}
      run: uv run pytest -v
